sudo: false
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "iojs"
  - "iojs-v1.0.0"
  - "0.12"
  - "0.11"
before_install:
  - "npm config set spin false"
  - '[ "${TRAVIS_NODE_VERSION}" != "4.1" ] || npm install -g npm@3'
  - "npm -v"